select * from sys.databases 
alter database[C:\USERS\YUHENGCHEN\DOCUMENTS\EASYSTORE.MDF]SET SINGLE_USER WITH ROLLBACK IMMEDIATE
alter database[C:\USERS\YUHENGCHEN\DOCUMENTS\EASYSTORE.MDF]COLLATE Chinese_PRC_CS_AI
alter database[C:\USERS\YUHENGCHEN\DOCUMENTS\EASYSTORE.MDF]SET MULTI_USER
